apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ros-network
spec:
  config: '{
    "cniVersion": "0.3.0",
    "name": "ros-network",
    "type": "macvlan",
    "master": "enp0s3",
    "mode": "bridge",
    "isDefaultgateway": true,
    "ipam": {
      "type": "host-local",
      "ranges": [
         [ {
           "subnet": "10.0.2.0/24",
           "rangeStart": "10.0.2.0.220",
           "rangeEnd": "10.0.2.0.240",
           "gateway": "10.0.2.2"
         } ]
      ]
    }
  }'
